Update Note for contributors
jellyfin/jellyfin-docs pull request #441
Opened 2020-11-18 06:35 UTC by Artiume

2020-11-18 07:37 UTC, nielsvanvelzen requested changes

2020-11-18 07:37 UTC, nielsvanvelzen commented on general/clients/index.md
> +> If you interested in helping out, please see our [contribution guide](xref:contrib-index) and feel free to contact us for more information!
```suggestion
> If you are interested in helping out, please see our [contribution guide](xref:contrib-index) and feel free to contact us for more information!
```

2020-11-18 07:53 UTC, nielsvanvelzen approved these changes

2020-11-18 07:54 UTC, nielsvanvelzen commented
The build is failing, not the fault of this PR though 🤔

2020-11-18 07:55 UTC, merged

2020-11-18 07:55 UTC, nielsvanvelzen commented
_yolomerge_

2020-12-06 16:49 UTC, HimbeersaftLP commented
The second paragraph of the note needs to be updated to accommodate the removal of that first sentence, because it sounds very weird the way it is now.