Add more CSS customization and CSS Themes
jellyfin/jellyfin-docs pull request #603
Opened 2021-12-16 05:39 UTC by prayag17

2021-12-16 06:58 UTC, Shadowghost commented on general/clients/css-customization.md
> +You can choose between Material Icons(Icon Pack used by Jellyfin) and Fontawesome icons.
```suggestion
You can choose between Material Icons (Icon Pack used by Jellyfin) and Fontawesome icons.
```

2021-12-16 06:58 UTC, Shadowghost commented on general/clients/css-customization.md
> +* [HInt Of Green](https://github.com/looi-wh/HintOfGreenCSS)
```suggestion
* [Hint of Green](https://github.com/looi-wh/HintOfGreenCSS)
```

2022-01-07 21:30 UTC, nielsvanvelzen requested changes
There's a bunch of (valid) linter warnings and you didn't fix the feedback from @Shadowghost (but you marked it as resolved).

2022-01-08 05:10 UTC, prayag17 commented
I have fixed the linter warnings and have made all the requested changes

2022-01-13 09:20 UTC, Shadowghost approved these changes

2022-01-13 09:22 UTC, nielsvanvelzen approved these changes

2022-01-13 09:22 UTC, merged